################################################################################
MLI_FILE		= cordova_video_player.mli
## Name which will be used in -package with ocamlfind
LIB_NAME		= cordova-plugin-videoplayer
################################################################################
